### ISSUE TITLE
Nested comments

### ISSUE THREAD

**Issue by bixiou** [airesis/airesis#102]
Hey !
Great job ! I use Airesis for an internal debate in my association, European Youth, and it's fantastic !
We have a demand for you :-)
In the forum part (that we use for the debates), would it be possible to enable nested comments, that is, when someone "answers" a comment, his answer his slightly on the left (same thing for the answer of the answer). We could imagine more fancy things, as the possibility (not) to show the answers of a comment, to rate a comment (-2/+2) and have the possibility to rank them by the average rate and so on. My point is, some improvements are possible in the forum part ;-)

**Comment by coorasse** [comment]
Hei,
the layout thing for nested comments I think is a cool idea.
Besides, I do not agree with ratings on forums, since voting and rating stuff belongs to the decisional process made in proposals and not in forums.
