### ISSUE TITLE
updates/chat

### ISSUE THREAD

**Issue by anhaga** [airesis/airesis#141]
Airesis is really great - I'm really impressed with your work. Is there any kind of chat app or system you're currently using to discuss work/updates? The team for the project I'm working on is following your recent updates very closely and we'd love to be able to ask questions and help out more easily. We'd also appreciate being able to get a general sense for what you have planned for the near future. This is mostly so that we know whether we will be able to contribute to the base project or whether we will need to fork, so it would be very helpful for us to sync up.

**Comment by coorasse** [comment]
We have no chat/mailing list but you can write to info@airesis.it or keep writing here :)
